### ISSUE TITLE
The depths in the NVIDIA-long-release dataset

### ISSUE THREAD

**Issue by danpeng2** [google/dynibar#27]
Hello, thank you so much for making your work open source.

The [depths](https://drive.google.com/drive/folders/1LRLkRfGLDr4TI4LTKumRM2X6rDweIkQa) in the NVIDIA-long-release dataset from dynamic-cvd?

Thank you very much.

**Comment by zhengqili** [comment]
Hi, these are precomputed disparity maps from our internal implementation of dynamic consistent video depth method, which you can use for Nvidia dataset.

**Comment by danpeng2** [comment]
Thank you for your reply.
