### ISSUE TITLE
Could you share the config file for training nvidia dataset?

### ISSUE THREAD

**Issue by dongxingMao** [google/dynibar#28]
Thank you for your great work~

**Comment by buesma** [comment]
I am not one of the authors but you can find the train configs for the Nvidia dataset in the provided [google drive](https://drive.google.com/drive/folders/1Gv6j_RvDG2WrpqEJWtx73u1tlCZKsPiM?usp=sharing).
The zip files each contain a checkpoint together with the config it was trained with.

**Comment by dongxingMao** [comment]
> 

Thank you very much, Buesma! I have located the configuration file under the "checkpoints/fine/dynamicface" directory. It appears that there is only one config file in the entire set of checkpoint folders, and the others do not have one.  Thank you again~

**Comment by dongxingMao** [comment]
> I am not one of the authors but you can find the train configs for the Nvidia dataset in the provided [google drive](https://drive.google.com/drive/folders/1Gv6j_RvDG2WrpqEJWtx73u1tlCZKsPiM?usp=sharing). The zip files each contain a checkpoint together with the config it was trained with.

Thank you very much, Buesma! I have located the configuration file under the "checkpoints/fine/dynamicface" directory. It appears that there is only one config file in the entire set of checkpoint folders, and the others do not have one. Thank you again~
