### ISSUE TITLE
Dynamic-cvd dependency problem.

### ISSUE THREAD

**Issue by taekkii** [google/dynibar#34]
Hi, thanks for sharing a great work!

I'm testing DAVIS dataset videos for your work, which requires refined disparity maps from dynamic-cvd, which happens to be failing a lot for my  case. I used COLMAP for camera calibration with masking dynamic object, and followed DAVIS preprocessing steps as described in dynamic-cvd repo. These are some of the results:

![compare_0000](https://github.com/google/dynibar/assets/73817342/b43f2f79-a7c0-4539-9544-22f9da471b4c)
![compare_0000](https://github.com/google/dynibar/assets/73817342/c0ff0ed5-5f84-4278-a09f-dda6ef28a409)

Can you share detailed preprocessing steps for data preparation Did you also experience failure like those? Or did you have any configuration changed from dynamic-cvd repo?

(p.s.) Also want to ask: did you run ORBSLAM2->COLMAP pose refinement step as depicted in dynamic-cvd?

**Comment by zhengqili** [comment]
No. We didn't use ORBSLAM2- COLMAP in our case. Could you tell me what is the first row and second row of the plots you showed?  It seems that initial/GT depth is wrong, which suggests the midas depth model you are using seems has something happening

**Comment by taekkii** [comment]
These are results from dynamic-cvd with some video from DAVIS dataset. I estimated initial pose with COLMAP, convert it to be correctly oriented as dynamic-cvd style. I'll check the MiDas model as you suggested. Thank you.
