### ISSUE TITLE
Why are the motion coefficients for last samples of the ray set to 0?

### ISSUE THREAD

**Issue by mra-h** [google/dynibar#35]
Hi,

Thanks for sharing this amazing work.

I was wondering why the motion coefficients for the last 10% samples of the ray get discarded? Is this for training stabilisation? As indicated [here](https://github.com/google/dynibar/blob/02b164144cce2d93aa4c5d87b418497286b2ae31/ibrnet/render_ray.py#L472). 

Thanks!

**Comment by zhengqili** [comment]
Yes. Sometimes the motion for far objects can be messy due to inaccurate depth priors. So we assume background motion is zero (and this should hold in most the time of real video )
