### ISSUE TITLE
The code is incomplete.

### ISSUE THREAD

**Issue by Wanggcong** [google/dynibar#41]
1) For the nvidia dataset, there is no training script.
2) For monocular datasets, no full data and no segmentation code.

Why?

**Comment by zhengqili** [comment]
Hi, please see Readme and some other issues: 
https://github.com/google/dynibar/issues/24
https://github.com/google/dynibar/issues/9
https://github.com/google/dynibar/issues/25

**Comment by Wanggcong** [comment]
Thank you for your reply. It is a great work. It would be nice to get access to the full code/data in the future if possible. I closed the issue.
