### ISSUE TITLE
Why are 2D optical flows rendered from 3D scene flows using neighbour camera poses?

### ISSUE THREAD

**Issue by mra-h** [google/dynibar#44]
Hi,

Thanks for the amazing work!

I am trying to understand how 2D optical flows are rendered from 3D scene flow. [Here](https://github.com/google/dynibar/blob/5412b55645fffb2656f6866fb44ce9a92af0c9a4/ibrnet/render_ray.py#L574), I found that to project 3D flows  `pts_3d_seq_ref` to 2D,  you use the nearest camera poses `src_cameras`. However, if I want to warp the reference view to its nearest frames using optical flow, shouldn't `pts_3d_seq_ref` be projected using the camera pose of the reference view? That would give the 2D displacement of each pixel in the reference to the neighbor camera. What is the reason to render using `src_cameras`?
 
Am I misunderstanding what 3D flows describe?

**Comment by zhengqili** [comment]
Hi, if you use the camera of reference view for projection, we will only get optical flow induced by scene motion (no camera motion involved in this case). However, to get full optical flow from reference to a target view, we need to take both camera and scene motions into consideration, and in this case, we need to use nearby camera poses as rendering viewpoint.
